[package]
name = "sched_deadline"
version = "0.1.0"
authors = ["Stephan Creutz <stephan.cr@gmx.de>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
libc = "0.2.68"
